"""
Crayfish Grid Hunter — Performance Monitor & Alert Engine
==========================================================
Provides real-time performance monitoring and multi-level alerting for
active grid trading positions. Designed to run as a background task
within the OpenClaw agent loop.

Monitoring Dimensions
---------------------
1. Grid Performance     — PnL tracking, fill rate, grid efficiency
2. Market Condition     — Volatility regime, trend drift detection
3. API Health           — Latency, error rate, fallback activation
4. Risk Management      — Drawdown, stop-loss proximity, exposure

Alert Levels
------------
CRITICAL  — Immediate action required (stop-loss breach, API failure)
HIGH      — Prompt review recommended (trend breakout, high drawdown)
MEDIUM    — Advisory notice (volatility regime change, slow API)
INFO      — Routine status update (PnL milestone, fill rate report)
"""

from __future__ import annotations

import math
import time
import uuid
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Callable, Dict, List, Optional, Tuple


# ============================================================
# Data Structures
# ============================================================

class AlertLevel(Enum):
    CRITICAL = "CRITICAL"
    HIGH     = "HIGH"
    MEDIUM   = "MEDIUM"
    INFO     = "INFO"


@dataclass
class Alert:
    """A single alert event generated by the monitor."""
    id: str
    level: AlertLevel
    category: str          # "grid_performance" | "market_condition" | "api_health" | "risk"
    symbol: str
    message: str
    value: float           # The numeric value that triggered the alert
    threshold: float       # The threshold that was crossed
    timestamp: datetime = field(default_factory=datetime.now)
    acknowledged: bool = False

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "level": self.level.value,
            "category": self.category,
            "symbol": self.symbol,
            "message": self.message,
            "value": round(self.value, 4),
            "threshold": round(self.threshold, 4),
            "timestamp": self.timestamp.isoformat(),
            "acknowledged": self.acknowledged,
        }

    def __str__(self) -> str:
        ts = self.timestamp.strftime("%H:%M:%S")
        return (f"[{ts}] [{self.level.value:<8}] [{self.category}] "
                f"{self.symbol}: {self.message} "
                f"(value={self.value:.4f}, threshold={self.threshold:.4f})")


@dataclass
class GridPosition:
    """Snapshot of an active grid trading position."""
    symbol: str
    grid_lower: float
    grid_upper: float
    grid_count: int
    entry_price: float
    current_price: float
    stop_loss: float
    invested_usdt: float
    realized_pnl: float = 0.0
    unrealized_pnl: float = 0.0
    total_fills: int = 0
    total_orders: int = 0
    start_time: datetime = field(default_factory=datetime.now)

    @property
    def fill_rate(self) -> float:
        """Percentage of grid orders that have been filled."""
        return (self.total_fills / self.total_orders * 100) if self.total_orders > 0 else 0.0

    @property
    def total_pnl(self) -> float:
        return self.realized_pnl + self.unrealized_pnl

    @property
    def pnl_pct(self) -> float:
        return (self.total_pnl / self.invested_usdt * 100) if self.invested_usdt > 0 else 0.0

    @property
    def price_in_range(self) -> bool:
        return self.grid_lower <= self.current_price <= self.grid_upper

    @property
    def distance_to_upper(self) -> float:
        """Percentage distance from current price to upper boundary."""
        return ((self.grid_upper - self.current_price) / self.grid_upper) * 100

    @property
    def distance_to_lower(self) -> float:
        """Percentage distance from current price to lower boundary."""
        return ((self.current_price - self.grid_lower) / self.grid_lower) * 100

    @property
    def distance_to_stop_loss(self) -> float:
        """Percentage distance from current price to stop-loss level."""
        return ((self.current_price - self.stop_loss) / self.stop_loss) * 100

    @property
    def runtime_hours(self) -> float:
        return (datetime.now() - self.start_time).total_seconds() / 3600


@dataclass
class ApiMetrics:
    """Tracks API call performance for health monitoring."""
    endpoint: str
    total_calls: int = 0
    error_count: int = 0
    total_latency_ms: float = 0.0
    last_error_time: Optional[datetime] = None
    using_fallback: bool = False
    latency_history: deque = field(default_factory=lambda: deque(maxlen=20))

    @property
    def error_rate(self) -> float:
        return (self.error_count / self.total_calls * 100) if self.total_calls > 0 else 0.0

    @property
    def avg_latency_ms(self) -> float:
        return (self.total_latency_ms / self.total_calls) if self.total_calls > 0 else 0.0

    @property
    def p95_latency_ms(self) -> float:
        """95th percentile latency from recent history."""
        if not self.latency_history:
            return 0.0
        sorted_latencies = sorted(self.latency_history)
        idx = int(len(sorted_latencies) * 0.95)
        return sorted_latencies[min(idx, len(sorted_latencies) - 1)]

    def record_call(self, latency_ms: float, success: bool):
        self.total_calls += 1
        self.total_latency_ms += latency_ms
        self.latency_history.append(latency_ms)
        if not success:
            self.error_count += 1
            self.last_error_time = datetime.now()


# ============================================================
# Threshold Configuration
# ============================================================

@dataclass
class MonitorThresholds:
    """Configurable thresholds for all alert conditions."""

    # --- Grid Performance ---
    pnl_loss_critical_pct: float = -5.0    # CRITICAL: PnL below -5%
    pnl_loss_high_pct: float = -3.0        # HIGH: PnL below -3%
    fill_rate_low_pct: float = 20.0        # MEDIUM: Fill rate below 20%
    fill_rate_stalled_pct: float = 5.0     # HIGH: Fill rate below 5% (grid stalled)

    # --- Market Condition ---
    boundary_proximity_critical_pct: float = 3.0   # CRITICAL: Price within 3% of boundary
    boundary_proximity_high_pct: float = 8.0        # HIGH: Price within 8% of boundary
    volume_spike_multiplier: float = 2.5            # CRITICAL: Volume > 2.5× 24h average
    trend_drift_pct: float = 2.0                    # MEDIUM: Price drifted >2% from entry

    # --- Risk Management ---
    stop_loss_proximity_critical_pct: float = 2.0  # CRITICAL: Within 2% of stop-loss
    stop_loss_proximity_high_pct: float = 5.0      # HIGH: Within 5% of stop-loss
    max_drawdown_critical_pct: float = 8.0         # CRITICAL: Drawdown > 8%
    max_drawdown_high_pct: float = 5.0             # HIGH: Drawdown > 5%

    # --- API Health ---
    api_latency_medium_ms: float = 1000.0   # MEDIUM: Avg latency > 1s
    api_latency_high_ms: float = 3000.0     # HIGH: Avg latency > 3s
    api_error_rate_medium_pct: float = 5.0  # MEDIUM: Error rate > 5%
    api_error_rate_high_pct: float = 20.0   # HIGH: Error rate > 20%


# ============================================================
# Core Monitor Engine
# ============================================================

class GridPerformanceMonitor:
    """
    Real-time performance monitor and alert engine for Crayfish Grid Hunter.

    Usage
    -----
    monitor = GridPerformanceMonitor()

    # Register an active position
    position = GridPosition(symbol="BTCUSDT", ...)
    monitor.register_position(position)

    # Update position state (call periodically)
    monitor.update_position("BTCUSDT", current_price=70500, ...)

    # Record API call metrics
    monitor.record_api_call("spot/klines", latency_ms=120, success=True)

    # Run all checks and collect alerts
    alerts = monitor.run_checks()
    for alert in alerts:
        print(alert)

    # Get a full status report
    report = monitor.generate_report()
    """

    def __init__(self, thresholds: Optional[MonitorThresholds] = None):
        self.thresholds = thresholds or MonitorThresholds()
        self.positions: Dict[str, GridPosition] = {}
        self.api_metrics: Dict[str, ApiMetrics] = {}
        self.alert_history: List[Alert] = []
        self._price_peaks: Dict[str, float] = {}   # For drawdown calculation
        self._alert_cooldowns: Dict[str, datetime] = {}
        self._alert_cooldown_minutes = 15

    # --------------------------------------------------------
    # Position Management
    # --------------------------------------------------------

    def register_position(self, position: GridPosition):
        """Register a new active grid position for monitoring."""
        self.positions[position.symbol] = position
        self._price_peaks[position.symbol] = position.current_price

    def update_position(self, symbol: str, current_price: float,
                        realized_pnl: float = None, unrealized_pnl: float = None,
                        total_fills: int = None, total_orders: int = None,
                        current_volume: float = None, avg_volume_24h: float = None):
        """Update position state with latest market data."""
        if symbol not in self.positions:
            return

        pos = self.positions[symbol]
        pos.current_price = current_price

        if realized_pnl is not None:
            pos.realized_pnl = realized_pnl
        if unrealized_pnl is not None:
            pos.unrealized_pnl = unrealized_pnl
        if total_fills is not None:
            pos.total_fills = total_fills
        if total_orders is not None:
            pos.total_orders = total_orders

        # Track price peak for drawdown calculation
        if current_price > self._price_peaks.get(symbol, 0):
            self._price_peaks[symbol] = current_price

        # Store volume data on position for alert checks
        if current_volume is not None:
            pos._current_volume = current_volume
        if avg_volume_24h is not None:
            pos._avg_volume_24h = avg_volume_24h

    def remove_position(self, symbol: str):
        """Remove a position from monitoring (e.g., grid closed)."""
        self.positions.pop(symbol, None)
        self._price_peaks.pop(symbol, None)

    # --------------------------------------------------------
    # API Metrics
    # --------------------------------------------------------

    def record_api_call(self, endpoint: str, latency_ms: float, success: bool):
        """Record the result of an API call for health tracking."""
        if endpoint not in self.api_metrics:
            self.api_metrics[endpoint] = ApiMetrics(endpoint=endpoint)
        self.api_metrics[endpoint].record_call(latency_ms, success)

    def mark_fallback_active(self, endpoint: str, using_fallback: bool):
        """Mark whether an endpoint is using its fallback URL."""
        if endpoint not in self.api_metrics:
            self.api_metrics[endpoint] = ApiMetrics(endpoint=endpoint)
        self.api_metrics[endpoint].using_fallback = using_fallback

    # --------------------------------------------------------
    # Alert Engine
    # --------------------------------------------------------

    def _make_alert(self, level: AlertLevel, category: str, symbol: str,
                    message: str, value: float, threshold: float,
                    cooldown_key: Optional[str] = None) -> Optional[Alert]:
        """Create an alert, respecting cooldown windows to avoid spam."""
        key = cooldown_key or f"{category}:{symbol}:{message[:30]}"
        last = self._alert_cooldowns.get(key)
        if last and (datetime.now() - last) < timedelta(minutes=self._alert_cooldown_minutes):
            return None  # Still in cooldown

        alert = Alert(
            id=str(uuid.uuid4())[:8],
            level=level,
            category=category,
            symbol=symbol,
            message=message,
            value=value,
            threshold=threshold,
        )
        self.alert_history.append(alert)
        self._alert_cooldowns[key] = datetime.now()
        return alert

    def _check_grid_performance(self, pos: GridPosition) -> List[Alert]:
        """Check PnL, fill rate, and grid efficiency."""
        alerts = []
        t = self.thresholds

        # PnL checks
        if pos.pnl_pct <= t.pnl_loss_critical_pct:
            a = self._make_alert(
                AlertLevel.CRITICAL, "grid_performance", pos.symbol,
                f"PnL critically low at {pos.pnl_pct:.2f}% — consider stopping the grid",
                pos.pnl_pct, t.pnl_loss_critical_pct,
                cooldown_key=f"pnl_critical:{pos.symbol}"
            )
            if a: alerts.append(a)
        elif pos.pnl_pct <= t.pnl_loss_high_pct:
            a = self._make_alert(
                AlertLevel.HIGH, "grid_performance", pos.symbol,
                f"PnL declining: {pos.pnl_pct:.2f}% (realized={pos.realized_pnl:.2f} USDT)",
                pos.pnl_pct, t.pnl_loss_high_pct,
                cooldown_key=f"pnl_high:{pos.symbol}"
            )
            if a: alerts.append(a)

        # Fill rate checks
        if pos.total_orders > 0:
            if pos.fill_rate <= t.fill_rate_stalled_pct:
                a = self._make_alert(
                    AlertLevel.HIGH, "grid_performance", pos.symbol,
                    f"Grid appears stalled — fill rate only {pos.fill_rate:.1f}%",
                    pos.fill_rate, t.fill_rate_stalled_pct,
                    cooldown_key=f"fill_stalled:{pos.symbol}"
                )
                if a: alerts.append(a)
            elif pos.fill_rate <= t.fill_rate_low_pct:
                a = self._make_alert(
                    AlertLevel.MEDIUM, "grid_performance", pos.symbol,
                    f"Low fill rate: {pos.fill_rate:.1f}% — market may be trending",
                    pos.fill_rate, t.fill_rate_low_pct,
                    cooldown_key=f"fill_low:{pos.symbol}"
                )
                if a: alerts.append(a)

        # Positive milestone
        if pos.pnl_pct >= 5.0:
            a = self._make_alert(
                AlertLevel.INFO, "grid_performance", pos.symbol,
                f"Grid milestone: PnL reached +{pos.pnl_pct:.2f}% "
                f"({pos.runtime_hours:.1f}h runtime, {pos.total_fills} fills)",
                pos.pnl_pct, 5.0,
                cooldown_key=f"milestone_5pct:{pos.symbol}"
            )
            if a: alerts.append(a)

        return alerts

    def _check_market_condition(self, pos: GridPosition) -> List[Alert]:
        """Check price proximity to boundaries, volume spikes, and trend drift."""
        alerts = []
        t = self.thresholds

        # Boundary proximity
        if pos.price_in_range:
            dist_to_upper = pos.distance_to_upper
            dist_to_lower = pos.distance_to_lower
            min_dist = min(dist_to_upper, dist_to_lower)
            boundary = "upper" if dist_to_upper < dist_to_lower else "lower"

            if min_dist <= t.boundary_proximity_critical_pct:
                a = self._make_alert(
                    AlertLevel.CRITICAL, "market_condition", pos.symbol,
                    f"Price {pos.current_price:.4f} is {min_dist:.1f}% from {boundary} boundary "
                    f"({pos.grid_upper if boundary == 'upper' else pos.grid_lower:.4f}) — "
                    f"breakout risk is HIGH",
                    min_dist, t.boundary_proximity_critical_pct,
                    cooldown_key=f"boundary_critical:{pos.symbol}"
                )
                if a: alerts.append(a)
            elif min_dist <= t.boundary_proximity_high_pct:
                a = self._make_alert(
                    AlertLevel.HIGH, "market_condition", pos.symbol,
                    f"Price approaching {boundary} boundary — "
                    f"{min_dist:.1f}% distance remaining",
                    min_dist, t.boundary_proximity_high_pct,
                    cooldown_key=f"boundary_high:{pos.symbol}"
                )
                if a: alerts.append(a)
        else:
            # Price has exited the grid range
            a = self._make_alert(
                AlertLevel.CRITICAL, "market_condition", pos.symbol,
                f"Price {pos.current_price:.4f} has EXITED the grid range "
                f"[{pos.grid_lower:.4f}, {pos.grid_upper:.4f}] — grid is inactive",
                pos.current_price, pos.grid_lower if pos.current_price < pos.grid_lower else pos.grid_upper,
                cooldown_key=f"out_of_range:{pos.symbol}"
            )
            if a: alerts.append(a)

        # Volume spike detection
        current_vol = getattr(pos, '_current_volume', None)
        avg_vol = getattr(pos, '_avg_volume_24h', None)
        if current_vol and avg_vol and avg_vol > 0:
            vol_ratio = current_vol / avg_vol
            if vol_ratio >= t.volume_spike_multiplier:
                a = self._make_alert(
                    AlertLevel.CRITICAL, "market_condition", pos.symbol,
                    f"Volume spike detected: {vol_ratio:.1f}× the 24h average — "
                    f"potential breakout imminent",
                    vol_ratio, t.volume_spike_multiplier,
                    cooldown_key=f"vol_spike:{pos.symbol}"
                )
                if a: alerts.append(a)

        # Trend drift from entry price
        drift_pct = abs((pos.current_price - pos.entry_price) / pos.entry_price * 100)
        if drift_pct >= t.trend_drift_pct:
            direction = "up" if pos.current_price > pos.entry_price else "down"
            a = self._make_alert(
                AlertLevel.MEDIUM, "market_condition", pos.symbol,
                f"Price has drifted {drift_pct:.1f}% {direction} from entry "
                f"({pos.entry_price:.4f}) — consider adjusting grid range",
                drift_pct, t.trend_drift_pct,
                cooldown_key=f"trend_drift:{pos.symbol}"
            )
            if a: alerts.append(a)

        return alerts

    def _check_risk(self, pos: GridPosition) -> List[Alert]:
        """Check stop-loss proximity and drawdown."""
        alerts = []
        t = self.thresholds

        # Stop-loss proximity
        dist_to_sl = pos.distance_to_stop_loss
        if dist_to_sl <= t.stop_loss_proximity_critical_pct:
            a = self._make_alert(
                AlertLevel.CRITICAL, "risk", pos.symbol,
                f"STOP-LOSS ALERT: Price {pos.current_price:.4f} is only "
                f"{dist_to_sl:.1f}% above stop-loss ({pos.stop_loss:.4f})",
                dist_to_sl, t.stop_loss_proximity_critical_pct,
                cooldown_key=f"sl_critical:{pos.symbol}"
            )
            if a: alerts.append(a)
        elif dist_to_sl <= t.stop_loss_proximity_high_pct:
            a = self._make_alert(
                AlertLevel.HIGH, "risk", pos.symbol,
                f"Approaching stop-loss: {dist_to_sl:.1f}% distance remaining "
                f"(stop at {pos.stop_loss:.4f})",
                dist_to_sl, t.stop_loss_proximity_high_pct,
                cooldown_key=f"sl_high:{pos.symbol}"
            )
            if a: alerts.append(a)

        # Drawdown from price peak
        peak = self._price_peaks.get(pos.symbol, pos.current_price)
        if peak > 0:
            drawdown_pct = ((peak - pos.current_price) / peak) * 100
            if drawdown_pct >= t.max_drawdown_critical_pct:
                a = self._make_alert(
                    AlertLevel.CRITICAL, "risk", pos.symbol,
                    f"Maximum drawdown reached {drawdown_pct:.1f}% from peak "
                    f"({peak:.4f} → {pos.current_price:.4f})",
                    drawdown_pct, t.max_drawdown_critical_pct,
                    cooldown_key=f"drawdown_critical:{pos.symbol}"
                )
                if a: alerts.append(a)
            elif drawdown_pct >= t.max_drawdown_high_pct:
                a = self._make_alert(
                    AlertLevel.HIGH, "risk", pos.symbol,
                    f"Drawdown warning: {drawdown_pct:.1f}% from recent peak ({peak:.4f})",
                    drawdown_pct, t.max_drawdown_high_pct,
                    cooldown_key=f"drawdown_high:{pos.symbol}"
                )
                if a: alerts.append(a)

        return alerts

    def _check_api_health(self) -> List[Alert]:
        """Check API latency and error rates across all endpoints."""
        alerts = []
        t = self.thresholds

        for endpoint, metrics in self.api_metrics.items():
            if metrics.total_calls < 3:
                continue  # Not enough data yet

            # Latency checks
            avg_lat = metrics.avg_latency_ms
            if avg_lat >= t.api_latency_high_ms:
                a = self._make_alert(
                    AlertLevel.HIGH, "api_health", endpoint,
                    f"High API latency: avg={avg_lat:.0f}ms, p95={metrics.p95_latency_ms:.0f}ms",
                    avg_lat, t.api_latency_high_ms,
                    cooldown_key=f"latency_high:{endpoint}"
                )
                if a: alerts.append(a)
            elif avg_lat >= t.api_latency_medium_ms:
                a = self._make_alert(
                    AlertLevel.MEDIUM, "api_health", endpoint,
                    f"Elevated API latency: avg={avg_lat:.0f}ms",
                    avg_lat, t.api_latency_medium_ms,
                    cooldown_key=f"latency_medium:{endpoint}"
                )
                if a: alerts.append(a)

            # Error rate checks
            err_rate = metrics.error_rate
            if err_rate >= t.api_error_rate_high_pct:
                a = self._make_alert(
                    AlertLevel.HIGH, "api_health", endpoint,
                    f"High API error rate: {err_rate:.1f}% "
                    f"({metrics.error_count}/{metrics.total_calls} calls failed)",
                    err_rate, t.api_error_rate_high_pct,
                    cooldown_key=f"error_high:{endpoint}"
                )
                if a: alerts.append(a)
            elif err_rate >= t.api_error_rate_medium_pct:
                a = self._make_alert(
                    AlertLevel.MEDIUM, "api_health", endpoint,
                    f"Elevated API error rate: {err_rate:.1f}%",
                    err_rate, t.api_error_rate_medium_pct,
                    cooldown_key=f"error_medium:{endpoint}"
                )
                if a: alerts.append(a)

            # Fallback notification
            if metrics.using_fallback:
                a = self._make_alert(
                    AlertLevel.MEDIUM, "api_health", endpoint,
                    f"Using fallback endpoint (primary unreachable)",
                    1.0, 1.0,
                    cooldown_key=f"fallback:{endpoint}"
                )
                if a: alerts.append(a)

        return alerts

    def run_checks(self) -> List[Alert]:
        """Run all monitoring checks and return new alerts."""
        new_alerts: List[Alert] = []

        for symbol, pos in self.positions.items():
            new_alerts.extend(self._check_grid_performance(pos))
            new_alerts.extend(self._check_market_condition(pos))
            new_alerts.extend(self._check_risk(pos))

        new_alerts.extend(self._check_api_health())

        # Sort by severity
        level_order = {
            AlertLevel.CRITICAL: 0,
            AlertLevel.HIGH: 1,
            AlertLevel.MEDIUM: 2,
            AlertLevel.INFO: 3,
        }
        new_alerts.sort(key=lambda a: level_order[a.level])
        return new_alerts

    # --------------------------------------------------------
    # Reporting
    # --------------------------------------------------------

    def generate_report(self) -> dict:
        """Generate a comprehensive status report for all monitored positions."""
        positions_report = []
        for symbol, pos in self.positions.items():
            peak = self._price_peaks.get(symbol, pos.current_price)
            drawdown = ((peak - pos.current_price) / peak * 100) if peak > 0 else 0.0
            positions_report.append({
                "symbol": symbol,
                "current_price": pos.current_price,
                "grid_range": [pos.grid_lower, pos.grid_upper],
                "stop_loss": pos.stop_loss,
                "price_in_range": pos.price_in_range,
                "pnl_pct": round(pos.pnl_pct, 4),
                "realized_pnl_usdt": round(pos.realized_pnl, 4),
                "unrealized_pnl_usdt": round(pos.unrealized_pnl, 4),
                "fill_rate_pct": round(pos.fill_rate, 2),
                "total_fills": pos.total_fills,
                "drawdown_from_peak_pct": round(drawdown, 4),
                "runtime_hours": round(pos.runtime_hours, 2),
                "distance_to_upper_pct": round(pos.distance_to_upper, 2),
                "distance_to_lower_pct": round(pos.distance_to_lower, 2),
                "distance_to_stop_loss_pct": round(pos.distance_to_stop_loss, 2),
            })

        api_report = {}
        for endpoint, m in self.api_metrics.items():
            api_report[endpoint] = {
                "total_calls": m.total_calls,
                "error_rate_pct": round(m.error_rate, 2),
                "avg_latency_ms": round(m.avg_latency_ms, 1),
                "p95_latency_ms": round(m.p95_latency_ms, 1),
                "using_fallback": m.using_fallback,
            }

        recent_alerts = [a.to_dict() for a in self.alert_history[-20:]]
        critical_count = sum(1 for a in self.alert_history if a.level == AlertLevel.CRITICAL)
        high_count = sum(1 for a in self.alert_history if a.level == AlertLevel.HIGH)

        return {
            "generated_at": datetime.now().isoformat(),
            "version": "4.4.0",
            "summary": {
                "active_positions": len(self.positions),
                "total_alerts_generated": len(self.alert_history),
                "critical_alerts": critical_count,
                "high_alerts": high_count,
            },
            "positions": positions_report,
            "api_health": api_report,
            "recent_alerts": recent_alerts,
        }

    def format_report(self) -> str:
        """Return a human-readable text report."""
        report = self.generate_report()
        lines = [
            "=" * 65,
            f"  CRAYFISH GRID HUNTER — PERFORMANCE MONITOR REPORT",
            f"  Generated: {report['generated_at']}",
            "=" * 65,
        ]

        summary = report["summary"]
        lines.append(
            f"  Active Positions: {summary['active_positions']}  |  "
            f"Alerts: {summary['total_alerts_generated']} total "
            f"({summary['critical_alerts']} CRITICAL, {summary['high_alerts']} HIGH)"
        )
        lines.append("")

        for pos in report["positions"]:
            status = "✓ IN RANGE" if pos["price_in_range"] else "✗ OUT OF RANGE"
            pnl_sign = "+" if pos["pnl_pct"] >= 0 else ""
            lines.append(f"  [{pos['symbol']}] {status}")
            lines.append(f"    Price : {pos['current_price']:.4f}  "
                         f"Range: [{pos['grid_range'][0]:.4f}, {pos['grid_range'][1]:.4f}]  "
                         f"SL: {pos['stop_loss']:.4f}")
            lines.append(f"    PnL   : {pnl_sign}{pos['pnl_pct']:.2f}%  "
                         f"(realized={pos['realized_pnl_usdt']:.2f} USDT)  "
                         f"Fill rate: {pos['fill_rate_pct']:.1f}%")
            lines.append(f"    Risk  : Drawdown={pos['drawdown_from_peak_pct']:.2f}%  "
                         f"→ Upper: {pos['distance_to_upper_pct']:.1f}%  "
                         f"→ Lower: {pos['distance_to_lower_pct']:.1f}%  "
                         f"→ SL: {pos['distance_to_stop_loss_pct']:.1f}%")
            lines.append(f"    Time  : {pos['runtime_hours']:.1f}h running  "
                         f"| {pos['total_fills']} fills")
            lines.append("")

        if report["api_health"]:
            lines.append("  API HEALTH")
            for ep, m in report["api_health"].items():
                fallback_tag = " [FALLBACK]" if m["using_fallback"] else ""
                lines.append(f"    {ep:<30} calls={m['total_calls']}  "
                             f"err={m['error_rate_pct']:.1f}%  "
                             f"avg={m['avg_latency_ms']:.0f}ms  "
                             f"p95={m['p95_latency_ms']:.0f}ms{fallback_tag}")
            lines.append("")

        if report["recent_alerts"]:
            lines.append("  RECENT ALERTS (last 5)")
            for a in report["recent_alerts"][-5:]:
                ts = a["timestamp"][11:19]
                lines.append(f"    [{ts}] [{a['level']:<8}] {a['symbol']}: {a['message']}")
            lines.append("")

        lines.append("=" * 65)
        return "\n".join(lines)


# ============================================================
# Convenience Factory
# ============================================================

def create_monitor(
    pnl_loss_critical_pct: float = -5.0,
    pnl_loss_high_pct: float = -3.0,
    boundary_proximity_critical_pct: float = 3.0,
    stop_loss_proximity_critical_pct: float = 2.0,
    volume_spike_multiplier: float = 2.5,
    api_latency_high_ms: float = 3000.0,
) -> GridPerformanceMonitor:
    """Create a pre-configured monitor with commonly adjusted thresholds."""
    thresholds = MonitorThresholds(
        pnl_loss_critical_pct=pnl_loss_critical_pct,
        pnl_loss_high_pct=pnl_loss_high_pct,
        boundary_proximity_critical_pct=boundary_proximity_critical_pct,
        stop_loss_proximity_critical_pct=stop_loss_proximity_critical_pct,
        volume_spike_multiplier=volume_spike_multiplier,
        api_latency_high_ms=api_latency_high_ms,
    )
    return GridPerformanceMonitor(thresholds=thresholds)
