"""
Crayfish Grid Hunter — Performance Monitor & Alert Engine
==========================================================
Provides real-time performance monitoring and multi-level alerting for
active grid trading positions. Designed to run as a background task
within the OpenClaw agent loop.

Monitoring Dimensions
---------------------
1. Grid Performance     — PnL tracking, fill rate, grid efficiency
2. Market Condition     — Volatility regime, trend drift detection
3. API Health           — Latency, error rate, fallback activation
4. Risk Management      — Drawdown, stop-loss proximity, exposure

Alert Levels
------------
CRITICAL  — Immediate action required (stop-loss breach, API failure)
HIGH      — Prompt review recommended (trend breakout, high drawdown)
MEDIUM    — Advisory notice (volatility regime change, slow API)
INFO      — Routine status update (PnL milestone, fill rate report)
"""

from __future__ import annotations

import math
import time
import uuid
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Callable, Dict, List, Optional, Tuple


# ============================================================
# Data Structures
# ============================================================

class AlertLevel(Enum):
    CRITICAL = "CRITICAL"
    HIGH     = "HIGH"
    MEDIUM   = "MEDIUM"
    INFO     = "INFO"


@dataclass
class Alert:
    """A single alert event generated by the monitor."""
    id: str
    level: AlertLevel
    category: str          # "grid_performance" | "market_condition" | "api_health" | "risk"
    symbol: str
    message: str
    value: float           # The numeric value that triggered the alert
    threshold: float       # The threshold that was crossed
    timestamp: datetime = field(default_factory=datetime.now)
    acknowledged: bool = False

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "level": self.level.value,
            "category": self.category,
            "symbol": self.symbol,
            "message": self.message,
            "value": round(self.value, 4),
            "threshold": round(self.threshold, 4),
            "timestamp": self.timestamp.isoformat(),
            "acknowledged": self.acknowledged,
        }

    def __str__(self) -> str:
        ts = self.timestamp.strftime("%H:%M:%S")
        return (f"[{ts}] [{self.level.value:<8}] [{self.category}] "
                f"{self.symbol}: {self.message} "
                f"(value={self.value:.4f}, threshold={self.threshold:.4f})")


@dataclass
class GridPosition:
    """Snapshot of an active grid trading position."""
    symbol: str
    grid_lower: float
    grid_upper: float
    grid_count: int
    entry_price: float
    current_price: float
    stop_loss: float
    invested_usdt: float
    realized_pnl: float = 0.0
    unrealized_pnl: float = 0.0
    total_fills: int = 0
    total_orders: int = 0
    start_time: datetime = field(default_factory=datetime.now)

    @property
    def fill_rate(self) -> float:
        """Percentage of grid orders that have been filled."""
        return (self.total_fills / self.total_orders * 100) if self.total_orders > 0 else 0.0

    @property
    def total_pnl(self) -> float:
        return self.realized_pnl + self.unrealized_pnl

    @property
    def pnl_pct(self) -> float:
        return (self.total_pnl / self.invested_usdt * 100) if self.invested_usdt > 0 else 0.0

    @property
    def price_in_range(self) -> bool:
        return self.grid_lower <= self.current_price <= self.grid_upper

    @property
    def distance_to_upper(self) -> float:
        """Percentage distance from current price to upper boundary."""
        return ((self.grid_upper - self.current_price) / self.grid_upper) * 100

    @property
    def distance_to_lower(self) -> float:
        """Percentage distance from current price to lower boundary."""
        return ((self.current_price - self.grid_lower) / self.grid_lower) * 100

    @property
    def distance_to_stop_loss(self) -> float:
        """Percentage distance from current price to stop-loss level."""
        return ((self.current_price - self.stop_loss) / self.stop_loss) * 100

    @property
    def runtime_hours(self) -> float:
        return (datetime.now() - self.start_time).total_seconds() / 3600


@dataclass
class ApiMetrics:
    """Tracks API call performance for health monitoring."""
    endpoint: str
    total_calls: int = 0
    error_count: int = 0
    total_latency_ms: float = 0.0
    last_error_time: Optional[datetime] = None
    using_fallback: bool = False
    latency_history: deque = field(default_factory=lambda: deque(maxlen=20))

    @property
    def error_rate(self) -> float:
        return (self.error_count / self.total_calls * 100) if self.total_calls > 0 else 0.0

    @property
    def avg_latency_ms(self) -> float:
        return (self.total_latency_ms / self.total_calls) if self.total_calls > 0 else 0.0

    @property
    def p95_latency_ms(self) -> float:
        """95th percentile latency from recent history."""
        if not self.latency_history:
            return 0.0
        sorted_latencies = sorted(self.latency_history)
        idx = int(len(sorted_latencies) * 0.95)
        return sorted_latencies[min(idx, len(sorted_latencies) - 1)]

    def record_call(self, latency_ms: float, success: bool):
        self.total_calls += 1
        self.total_latency_ms += latency_ms
        self.latency_history.append(latency_ms)
        if not success:
            self.error_count += 1
            self.last_error_time = datetime.now()


# ============================================================
# Threshold Configuration
# ============================================================

@dataclass
class MonitorThresholds:
    """Configurable thresholds for all alert conditions."""

    # --- Grid Performance ---
    pnl_loss_critical_pct: float = -5.0    # CRITICAL: PnL below -5%
    pnl_loss_high_pct: float = -3.0        # HIGH: PnL below -3%
    fill_rate_low_pct: float = 20.0        # MEDIUM: Fill rate below 20%
    fill_rate_stalled_pct: float = 5.0     # HIGH: Fill rate below 5% (grid stalled)

    # --- Market Condition ---
    boundary_proximity_critical_pct: float = 3.0   # CRITICAL: Price within 3% of boundary
    boundary_proximity_high_pct: float = 8.0        # HIGH: Price within 8% of boundary
    volume_spike_multiplier: float = 2.5            # CRITICAL: Volume > 2.5× 24h average
    trend_drift_pct: float = 2.0                    # MEDIUM: Price drifted >2% from entry

    # --- Risk Management ---
    stop_loss_proximity_critical_pct: float = 2.0  # CRITICAL: Within 2% of stop-loss
    stop_loss_proximity_high_pct: float = 5.0      # HIGH: Within 5% of stop-loss
    max_drawdown_critical_pct: float = 8.0         # CRITICAL: Drawdown > 8%
    max_drawdown_high_pct: float = 5.0             # HIGH: Drawdown > 5%

    # --- API Health ---
    api_latency_medium_ms: float = 1000.0   # MEDIUM: Avg latency > 1s
    api_latency_high_ms: float = 3000.0     # HIGH: Avg latency > 3s
    api_error_rate_medium_pct: float = 5.0  # MEDIUM: Error rate > 5%
    api_error_rate_high_pct: float = 20.0   # HIGH: Error rate > 20%

    # --- Futures-Specific (v5.0) ---
    liquidation_proximity_pct: float = 10.0  # CRITICAL: Within 10% of liquidation price
    funding_rate_high_pct: float = 0.003     # HIGH: Funding rate > 0.3% (long grid paying)
    funding_rate_extreme_pct: float = 0.005  # CRITICAL: Funding rate > 0.5%


# ============================================================
# Core Monitor Engine
# ============================================================

class GridPerformanceMonitor:
    """
    Real-time performance monitor and alert engine for Crayfish Grid Hunter.

    Usage
    -----
    monitor = GridPerformanceMonitor()

    # Register an active position
    position = GridPosition(symbol="BTCUSDT", ...)
    monitor.register_position(position)

    # Update position state (call periodically)
    monitor.update_position("BTCUSDT", current_price=70500, ...)

    # Record API call metrics
    monitor.record_api_call("spot/klines", latency_ms=120, success=True)

    # Run all checks and collect alerts
    alerts = monitor.run_checks()
    for alert in alerts:
        print(alert)

    # Get a full status report
    report = monitor.generate_report()
    """

    def __init__(self, thresholds: Optional[MonitorThresholds] = None):
        self.thresholds = thresholds or MonitorThresholds()
        self.positions: Dict[str, GridPosition] = {}
        self.api_metrics: Dict[str, ApiMetrics] = {}
        self.alert_history: List[Alert] = []
        self._price_peaks: Dict[str, float] = {}   # For drawdown calculation
        self._alert_cooldowns: Dict[str, datetime] = {}
        self._alert_cooldown_minutes = 15

    # --------------------------------------------------------
    # Position Management
    # --------------------------------------------------------

    def register_position(self, position: GridPosition):
        """Register a new active grid position for monitoring."""
        self.positions[position.symbol] = position
        self._price_peaks[position.symbol] = position.current_price

    def update_position(self, symbol: str, current_price: float,
                        realized_pnl: float = None, unrealized_pnl: float = None,
                        total_fills: int = None, total_orders: int = None,
                        current_volume: float = None, avg_volume_24h: float = None):
        """Update position state with latest market data."""
        if symbol not in self.positions:
            return

        pos = self.positions[symbol]
        pos.current_price = current_price

        if realized_pnl is not None:
            pos.realized_pnl = realized_pnl
        if unrealized_pnl is not None:
            pos.unrealized_pnl = unrealized_pnl
        if total_fills is not None:
            pos.total_fills = total_fills
        if total_orders is not None:
            pos.total_orders = total_orders

        # Track price peak for drawdown calculation
        if current_price > self._price_peaks.get(symbol, 0):
            self._price_peaks[symbol] = current_price

        # Store volume data on position for alert checks
        if current_volume is not None:
            pos._current_volume = current_volume
        if avg_volume_24h is not None:
            pos._avg_volume_24h = avg_volume_24h

    def remove_position(self, symbol: str):
        """Remove a position from monitoring (e.g., grid closed)."""
        self.positions.pop(symbol, None)
        self._price_peaks.pop(symbol, None)

    # --------------------------------------------------------
    # API Metrics
    # --------------------------------------------------------

    def record_api_call(self, endpoint: str, latency_ms: float, success: bool):
        """Record the result of an API call for health tracking."""
        if endpoint not in self.api_metrics:
            self.api_metrics[endpoint] = ApiMetrics(endpoint=endpoint)
        self.api_metrics[endpoint].record_call(latency_ms, success)

    def mark_fallback_active(self, endpoint: str, using_fallback: bool):
        """Mark whether an endpoint is using its fallback URL."""
        if endpoint not in self.api_metrics:
            self.api_metrics[endpoint] = ApiMetrics(endpoint=endpoint)
        self.api_metrics[endpoint].using_fallback = using_fallback

    # --------------------------------------------------------
    # Alert Engine
    # --------------------------------------------------------

    def _make_alert(self, level: AlertLevel, category: str, symbol: str,
                    message: str, value: float, threshold: float,
                    cooldown_key: Optional[str] = None) -> Optional[Alert]:
        """Create an alert, respecting cooldown windows to avoid spam."""
        key = cooldown_key or f"{category}:{symbol}:{message[:30]}"
        last = self._alert_cooldowns.get(key)
        if last and (datetime.now() - last) < timedelta(minutes=self._alert_cooldown_minutes):
            return None  # Still in cooldown

        alert = Alert(
            id=str(uuid.uuid4())[:8],
            level=level,
            category=category,
            symbol=symbol,
            message=message,
            value=value,
            threshold=threshold,
        )
        self.alert_history.append(alert)
        self._alert_cooldowns[key] = datetime.now()
        return alert

    def _check_grid_performance(self, pos: GridPosition) -> List[Alert]:
        """Check PnL, fill rate, and grid efficiency."""
        alerts = []
        t = self.thresholds

        # PnL checks
        if pos.pnl_pct <= t.pnl_loss_critical_pct:
            a = self._make_alert(
                AlertLevel.CRITICAL, "grid_performance", pos.symbol,
                f"PnL critically low at {pos.pnl_pct:.2f}% — consider stopping the grid",
                pos.pnl_pct, t.pnl_loss_critical_pct,
                cooldown_key=f"pnl_critical:{pos.symbol}"
            )
            if a: alerts.append(a)
        elif pos.pnl_pct <= t.pnl_loss_high_pct:
            a = self._make_alert(
                AlertLevel.HIGH, "grid_performance", pos.symbol,
                f"PnL declining: {pos.pnl_pct:.2f}% (realized={pos.realized_pnl:.2f} USDT)",
                pos.pnl_pct, t.pnl_loss_high_pct,
                cooldown_key=f"pnl_high:{pos.symbol}"
            )
            if a: alerts.append(a)

        # Fill rate checks
        if pos.total_orders > 0:
            if pos.fill_rate <= t.fill_rate_stalled_pct:
                a = self._make_alert(
                    AlertLevel.HIGH, "grid_performance", pos.symbol,
                    f"Grid appears stalled — fill rate only {pos.fill_rate:.1f}%",
                    pos.fill_rate, t.fill_rate_stalled_pct,
                    cooldown_key=f"fill_stalled:{pos.symbol}"
                )
                if a: alerts.append(a)
            elif pos.fill_rate <= t.fill_rate_low_pct:
                a = self._make_alert(
                    AlertLevel.MEDIUM, "grid_performance", pos.symbol,
                    f"Low fill rate: {pos.fill_rate:.1f}% — market may be trending",
                    pos.fill_rate, t.fill_rate_low_pct,
                    cooldown_key=f"fill_low:{pos.symbol}"
                )
                if a: alerts.append(a)

        # Positive milestone
        if pos.pnl_pct >= 5.0:
            a = self._make_alert(
                AlertLevel.INFO, "grid_performance", pos.symbol,
                f"Grid milestone: PnL reached +{pos.pnl_pct:.2f}% "
                f"({pos.runtime_hours:.1f}h runtime, {pos.total_fills} fills)",
                pos.pnl_pct, 5.0,
                cooldown_key=f"milestone_5pct:{pos.symbol}"
            )
            if a: alerts.append(a)

        return alerts

    def _check_market_condition(self, pos: GridPosition) -> List[Alert]:
        """Check price proximity to boundaries, volume spikes, and trend drift."""
        alerts = []
        t = self.thresholds

        # Boundary proximity
        if pos.price_in_range:
            dist_to_upper = pos.distance_to_upper
            dist_to_lower = pos.distance_to_lower
            min_dist = min(dist_to_upper, dist_to_lower)
            boundary = "upper" if dist_to_upper < dist_to_lower else "lower"

            if min_dist <= t.boundary_proximity_critical_pct:
                a = self._make_alert(
                    AlertLevel.CRITICAL, "market_condition", pos.symbol,
                    f"Price {pos.current_price:.4f} is {min_dist:.1f}% from {boundary} boundary "
                    f"({pos.grid_upper if boundary == 'upper' else pos.grid_lower:.4f}) — "
                    f"breakout risk is HIGH",
                    min_dist, t.boundary_proximity_critical_pct,
                    cooldown_key=f"boundary_critical:{pos.symbol}"
                )
                if a: alerts.append(a)
            elif min_dist <= t.boundary_proximity_high_pct:
                a = self._make_alert(
                    AlertLevel.HIGH, "market_condition", pos.symbol,
                    f"Price approaching {boundary} boundary — "
                    f"{min_dist:.1f}% distance remaining",
                    min_dist, t.boundary_proximity_high_pct,
                    cooldown_key=f"boundary_high:{pos.symbol}"
                )
                if a: alerts.append(a)
        else:
            # Price has exited the grid range
            a = self._make_alert(
                AlertLevel.CRITICAL, "market_condition", pos.symbol,
                f"Price {pos.current_price:.4f} has EXITED the grid range "
                f"[{pos.grid_lower:.4f}, {pos.grid_upper:.4f}] — grid is inactive",
                pos.current_price, pos.grid_lower if pos.current_price < pos.grid_lower else pos.grid_upper,
                cooldown_key=f"out_of_range:{pos.symbol}"
            )
            if a: alerts.append(a)

        # Volume spike detection
        current_vol = getattr(pos, '_current_volume', None)
        avg_vol = getattr(pos, '_avg_volume_24h', None)
        if current_vol and avg_vol and avg_vol > 0:
            vol_ratio = current_vol / avg_vol
            if vol_ratio >= t.volume_spike_multiplier:
                a = self._make_alert(
                    AlertLevel.CRITICAL, "market_condition", pos.symbol,
                    f"Volume spike detected: {vol_ratio:.1f}× the 24h average — "
                    f"potential breakout imminent",
                    vol_ratio, t.volume_spike_multiplier,
                    cooldown_key=f"vol_spike:{pos.symbol}"
                )
                if a: alerts.append(a)

        # Trend drift from entry price
        drift_pct = abs((pos.current_price - pos.entry_price) / pos.entry_price * 100)
        if drift_pct >= t.trend_drift_pct:
            direction = "up" if pos.current_price > pos.entry_price else "down"
            a = self._make_alert(
                AlertLevel.MEDIUM, "market_condition", pos.symbol,
                f"Price has drifted {drift_pct:.1f}% {direction} from entry "
                f"({pos.entry_price:.4f}) — consider adjusting grid range",
                drift_pct, t.trend_drift_pct,
                cooldown_key=f"trend_drift:{pos.symbol}"
            )
            if a: alerts.append(a)

        return alerts

    def _check_risk(self, pos: GridPosition) -> List[Alert]:
        """Check stop-loss proximity and drawdown."""
        alerts = []
        t = self.thresholds

        # Stop-loss proximity
        dist_to_sl = pos.distance_to_stop_loss
        if dist_to_sl <= t.stop_loss_proximity_critical_pct:
            a = self._make_alert(
                AlertLevel.CRITICAL, "risk", pos.symbol,
                f"STOP-LOSS ALERT: Price {pos.current_price:.4f} is only "
                f"{dist_to_sl:.1f}% above stop-loss ({pos.stop_loss:.4f})",
                dist_to_sl, t.stop_loss_proximity_critical_pct,
                cooldown_key=f"sl_critical:{pos.symbol}"
            )
            if a: alerts.append(a)
        elif dist_to_sl <= t.stop_loss_proximity_high_pct:
            a = self._make_alert(
                AlertLevel.HIGH, "risk", pos.symbol,
                f"Approaching stop-loss: {dist_to_sl:.1f}% distance remaining "
                f"(stop at {pos.stop_loss:.4f})",
                dist_to_sl, t.stop_loss_proximity_high_pct,
                cooldown_key=f"sl_high:{pos.symbol}"
            )
            if a: alerts.append(a)

        # Drawdown from price peak
        peak = self._price_peaks.get(pos.symbol, pos.current_price)
        if peak > 0:
            drawdown_pct = ((peak - pos.current_price) / peak) * 100
            if drawdown_pct >= t.max_drawdown_critical_pct:
                a = self._make_alert(
                    AlertLevel.CRITICAL, "risk", pos.symbol,
                    f"Maximum drawdown reached {drawdown_pct:.1f}% from peak "
                    f"({peak:.4f} → {pos.current_price:.4f})",
                    drawdown_pct, t.max_drawdown_critical_pct,
                    cooldown_key=f"drawdown_critical:{pos.symbol}"
                )
                if a: alerts.append(a)
            elif drawdown_pct >= t.max_drawdown_high_pct:
                a = self._make_alert(
                    AlertLevel.HIGH, "risk", pos.symbol,
                    f"Drawdown warning: {drawdown_pct:.1f}% from recent peak ({peak:.4f})",
                    drawdown_pct, t.max_drawdown_high_pct,
                    cooldown_key=f"drawdown_high:{pos.symbol}"
                )
                if a: alerts.append(a)

        return alerts

    def _check_api_health(self) -> List[Alert]:
        """Check API latency and error rates across all endpoints."""
        alerts = []
        t = self.thresholds

        for endpoint, metrics in self.api_metrics.items():
            if metrics.total_calls < 3:
                continue  # Not enough data yet

            # Latency checks
            avg_lat = metrics.avg_latency_ms
            if avg_lat >= t.api_latency_high_ms:
                a = self._make_alert(
                    AlertLevel.HIGH, "api_health", endpoint,
                    f"High API latency: avg={avg_lat:.0f}ms, p95={metrics.p95_latency_ms:.0f}ms",
                    avg_lat, t.api_latency_high_ms,
                    cooldown_key=f"latency_high:{endpoint}"
                )
                if a: alerts.append(a)
            elif avg_lat >= t.api_latency_medium_ms:
                a = self._make_alert(
                    AlertLevel.MEDIUM, "api_health", endpoint,
                    f"Elevated API latency: avg={avg_lat:.0f}ms",
                    avg_lat, t.api_latency_medium_ms,
                    cooldown_key=f"latency_medium:{endpoint}"
                )
                if a: alerts.append(a)

            # Error rate checks
            err_rate = metrics.error_rate
            if err_rate >= t.api_error_rate_high_pct:
                a = self._make_alert(
                    AlertLevel.HIGH, "api_health", endpoint,
                    f"High API error rate: {err_rate:.1f}% "
                    f"({metrics.error_count}/{metrics.total_calls} calls failed)",
                    err_rate, t.api_error_rate_high_pct,
                    cooldown_key=f"error_high:{endpoint}"
                )
                if a: alerts.append(a)
            elif err_rate >= t.api_error_rate_medium_pct:
                a = self._make_alert(
                    AlertLevel.MEDIUM, "api_health", endpoint,
                    f"Elevated API error rate: {err_rate:.1f}%",
                    err_rate, t.api_error_rate_medium_pct,
                    cooldown_key=f"error_medium:{endpoint}"
                )
                if a: alerts.append(a)

            # Fallback notification
            if metrics.using_fallback:
                a = self._make_alert(
                    AlertLevel.MEDIUM, "api_health", endpoint,
                    f"Using fallback endpoint (primary unreachable)",
                    1.0, 1.0,
                    cooldown_key=f"fallback:{endpoint}"
                )
                if a: alerts.append(a)

        return alerts

    def run_checks(self) -> List[Alert]:
        """Run all monitoring checks and return new alerts."""
        new_alerts: List[Alert] = []

        for symbol, pos in self.positions.items():
            new_alerts.extend(self._check_grid_performance(pos))
            new_alerts.extend(self._check_market_condition(pos))
            new_alerts.extend(self._check_risk(pos))

        new_alerts.extend(self._check_api_health())

        # Sort by severity
        level_order = {
            AlertLevel.CRITICAL: 0,
            AlertLevel.HIGH: 1,
            AlertLevel.MEDIUM: 2,
            AlertLevel.INFO: 3,
        }
        new_alerts.sort(key=lambda a: level_order[a.level])
        return new_alerts

    # --------------------------------------------------------
    # Reporting
    # --------------------------------------------------------

    def generate_report(self) -> dict:
        """Generate a comprehensive status report for all monitored positions."""
        positions_report = []
        for symbol, pos in self.positions.items():
            peak = self._price_peaks.get(symbol, pos.current_price)
            drawdown = ((peak - pos.current_price) / peak * 100) if peak > 0 else 0.0
            positions_report.append({
                "symbol": symbol,
                "current_price": pos.current_price,
                "grid_range": [pos.grid_lower, pos.grid_upper],
                "stop_loss": pos.stop_loss,
                "price_in_range": pos.price_in_range,
                "pnl_pct": round(pos.pnl_pct, 4),
                "realized_pnl_usdt": round(pos.realized_pnl, 4),
                "unrealized_pnl_usdt": round(pos.unrealized_pnl, 4),
                "fill_rate_pct": round(pos.fill_rate, 2),
                "total_fills": pos.total_fills,
                "drawdown_from_peak_pct": round(drawdown, 4),
                "runtime_hours": round(pos.runtime_hours, 2),
                "distance_to_upper_pct": round(pos.distance_to_upper, 2),
                "distance_to_lower_pct": round(pos.distance_to_lower, 2),
                "distance_to_stop_loss_pct": round(pos.distance_to_stop_loss, 2),
            })

        api_report = {}
        for endpoint, m in self.api_metrics.items():
            api_report[endpoint] = {
                "total_calls": m.total_calls,
                "error_rate_pct": round(m.error_rate, 2),
                "avg_latency_ms": round(m.avg_latency_ms, 1),
                "p95_latency_ms": round(m.p95_latency_ms, 1),
                "using_fallback": m.using_fallback,
            }

        recent_alerts = [a.to_dict() for a in self.alert_history[-20:]]
        critical_count = sum(1 for a in self.alert_history if a.level == AlertLevel.CRITICAL)
        high_count = sum(1 for a in self.alert_history if a.level == AlertLevel.HIGH)

        return {
            "generated_at": datetime.now().isoformat(),
            "version": "1.0.0",
            "summary": {
                "active_positions": len(self.positions),
                "total_alerts_generated": len(self.alert_history),
                "critical_alerts": critical_count,
                "high_alerts": high_count,
            },
            "positions": positions_report,
            "api_health": api_report,
            "recent_alerts": recent_alerts,
        }

    def format_report(self) -> str:
        """Return a human-readable text report."""
        report = self.generate_report()
        lines = [
            "=" * 65,
            f"  CRAYFISH GRID HUNTER — PERFORMANCE MONITOR REPORT",
            f"  Generated: {report['generated_at']}",
            "=" * 65,
        ]

        summary = report["summary"]
        lines.append(
            f"  Active Positions: {summary['active_positions']}  |  "
            f"Alerts: {summary['total_alerts_generated']} total "
            f"({summary['critical_alerts']} CRITICAL, {summary['high_alerts']} HIGH)"
        )
        lines.append("")

        for pos in report["positions"]:
            status = "✓ IN RANGE" if pos["price_in_range"] else "✗ OUT OF RANGE"
            pnl_sign = "+" if pos["pnl_pct"] >= 0 else ""
            lines.append(f"  [{pos['symbol']}] {status}")
            lines.append(f"    Price : {pos['current_price']:.4f}  "
                         f"Range: [{pos['grid_range'][0]:.4f}, {pos['grid_range'][1]:.4f}]  "
                         f"SL: {pos['stop_loss']:.4f}")
            lines.append(f"    PnL   : {pnl_sign}{pos['pnl_pct']:.2f}%  "
                         f"(realized={pos['realized_pnl_usdt']:.2f} USDT)  "
                         f"Fill rate: {pos['fill_rate_pct']:.1f}%")
            lines.append(f"    Risk  : Drawdown={pos['drawdown_from_peak_pct']:.2f}%  "
                         f"→ Upper: {pos['distance_to_upper_pct']:.1f}%  "
                         f"→ Lower: {pos['distance_to_lower_pct']:.1f}%  "
                         f"→ SL: {pos['distance_to_stop_loss_pct']:.1f}%")
            lines.append(f"    Time  : {pos['runtime_hours']:.1f}h running  "
                         f"| {pos['total_fills']} fills")
            lines.append("")

        if report["api_health"]:
            lines.append("  API HEALTH")
            for ep, m in report["api_health"].items():
                fallback_tag = " [FALLBACK]" if m["using_fallback"] else ""
                lines.append(f"    {ep:<30} calls={m['total_calls']}  "
                             f"err={m['error_rate_pct']:.1f}%  "
                             f"avg={m['avg_latency_ms']:.0f}ms  "
                             f"p95={m['p95_latency_ms']:.0f}ms{fallback_tag}")
            lines.append("")

        if report["recent_alerts"]:
            lines.append("  RECENT ALERTS (last 5)")
            for a in report["recent_alerts"][-5:]:
                ts = a["timestamp"][11:19]
                lines.append(f"    [{ts}] [{a['level']:<8}] {a['symbol']}: {a['message']}")
            lines.append("")

        lines.append("=" * 65)
        return "\n".join(lines)


# ============================================================
# Convenience Factory
# ============================================================

# ============================================================
# Futures-Specific Monitoring Helpers (v5.0)
# ============================================================

def check_funding_and_liquidation(
    symbol: str,
    current_price: float,
    funding_rate: float,
    liquidation_price: float,
    stop_loss_price: float,
    grid_direction: str = "neutral",
    thresholds: Optional[MonitorThresholds] = None,
) -> List[Alert]:
    """
    Futures-specific check for funding rate anomalies and liquidation proximity.

    This function implements the monitoring logic described in SKILL.md Step 5.5:

        if funding_rate < 0 and grid_direction == 'long':
            alert_funding_profit(expected_yield)

        if price < stop_loss_5pct or price < liquidation_price:
            close_all_grids()

    Parameters
    ----------
    symbol : str
        Trading symbol (e.g. 'BTCUSDT')
    current_price : float
        Current mark price from /fapi/v1/premiumIndex
    funding_rate : float
        Latest funding rate from /fapi/v1/premiumIndex (e.g. -0.00012)
    liquidation_price : float
        Estimated liquidation price (from GridParameters.liquidation_price)
    stop_loss_price : float
        Hard stop-loss price (5% below lower bound)
    grid_direction : str
        'long', 'short', or 'neutral'
    thresholds : MonitorThresholds, optional
        Custom thresholds; uses defaults if None

    Returns
    -------
    List[Alert]
        List of triggered alerts (may be empty)
    """
    if thresholds is None:
        thresholds = MonitorThresholds()

    alerts: List[Alert] = []
    now = datetime.now()

    def _alert(level, category, message, value, threshold):
        return Alert(
            id=str(uuid.uuid4()),
            level=level,
            category=category,
            symbol=symbol,
            message=message,
            value=value,
            threshold=threshold,
            timestamp=now,
        )

    # --- Emergency exit conditions ---
    if current_price <= stop_loss_price:
        alerts.append(_alert(
            AlertLevel.CRITICAL, "futures_risk",
            f"EMERGENCY: Price {current_price:.4f} has breached stop-loss {stop_loss_price:.4f} "
            f"— CLOSE ALL GRID ORDERS IMMEDIATELY",
            current_price, stop_loss_price,
        ))

    if liquidation_price > 0 and current_price <= liquidation_price * 1.05:
        pct_from_liq = ((current_price - liquidation_price) / liquidation_price) * 100
        alerts.append(_alert(
            AlertLevel.CRITICAL, "futures_risk",
            f"EMERGENCY: Price {current_price:.4f} is within {pct_from_liq:.1f}% of liquidation "
            f"price {liquidation_price:.4f} — reduce leverage or add margin NOW",
            pct_from_liq, 5.0,
        ))
    elif liquidation_price > 0:
        pct_from_liq = ((current_price - liquidation_price) / liquidation_price) * 100
        if pct_from_liq <= thresholds.liquidation_proximity_pct:
            alerts.append(_alert(
                AlertLevel.HIGH, "futures_risk",
                f"Price {current_price:.4f} is {pct_from_liq:.1f}% above liquidation price "
                f"{liquidation_price:.4f} — consider reducing position size",
                pct_from_liq, thresholds.liquidation_proximity_pct,
            ))

    # --- Funding rate analysis ---
    daily_yield_pct = abs(funding_rate) * 3 * 100  # 3 settlements per day

    if funding_rate < 0 and grid_direction in ("long", "neutral"):
        # Negative funding = long positions receive funding
        alerts.append(_alert(
            AlertLevel.INFO, "futures_funding",
            f"Negative funding rate {funding_rate*100:.4f}% — long grid earns "
            f"~{daily_yield_pct:.3f}%/day ({abs(funding_rate)*100:.4f}% per 8h × 3)",
            abs(funding_rate), 0.0,
        ))

    elif funding_rate >= thresholds.funding_rate_extreme_pct and grid_direction in ("long", "neutral"):
        alerts.append(_alert(
            AlertLevel.CRITICAL, "futures_funding",
            f"EXTREME funding rate {funding_rate*100:.4f}% — long grid paying "
            f"{daily_yield_pct:.3f}%/day, severely impacting grid profitability",
            funding_rate, thresholds.funding_rate_extreme_pct,
        ))

    elif funding_rate >= thresholds.funding_rate_high_pct and grid_direction in ("long", "neutral"):
        alerts.append(_alert(
            AlertLevel.HIGH, "futures_funding",
            f"High funding rate {funding_rate*100:.4f}% — long grid paying "
            f"{daily_yield_pct:.3f}%/day, consider switching to short-biased grid",
            funding_rate, thresholds.funding_rate_high_pct,
        ))

    elif funding_rate > 0 and grid_direction == "short":
        # Positive funding = short positions receive funding
        alerts.append(_alert(
            AlertLevel.INFO, "futures_funding",
            f"Positive funding rate {funding_rate*100:.4f}% — short grid earns "
            f"~{daily_yield_pct:.3f}%/day",
            funding_rate, 0.0,
        ))

    return alerts


def create_monitor(
    pnl_loss_critical_pct: float = -5.0,
    pnl_loss_high_pct: float = -3.0,
    boundary_proximity_critical_pct: float = 3.0,
    stop_loss_proximity_critical_pct: float = 2.0,
    volume_spike_multiplier: float = 2.5,
    api_latency_high_ms: float = 3000.0,
    webhook_url: Optional[str] = None,
) -> GridPerformanceMonitor:
    """Create a pre-configured monitor with commonly adjusted thresholds."""
    thresholds = MonitorThresholds(
        pnl_loss_critical_pct=pnl_loss_critical_pct,
        pnl_loss_high_pct=pnl_loss_high_pct,
        boundary_proximity_critical_pct=boundary_proximity_critical_pct,
        stop_loss_proximity_critical_pct=stop_loss_proximity_critical_pct,
        volume_spike_multiplier=volume_spike_multiplier,
        api_latency_high_ms=api_latency_high_ms,
    )
    monitor = GridPerformanceMonitor(thresholds=thresholds)
    if webhook_url:
        monitor.set_webhook(webhook_url)
    return monitor


# ============================================================
# v5.3 — Enhanced Real-Time Performance Monitoring
# ============================================================

@dataclass
class PerformanceSnapshot:
    """Point-in-time snapshot for performance tracking history."""
    timestamp: datetime
    symbol: str
    price: float
    pnl_pct: float
    fill_rate: float
    volatility_regime: str  # "low" | "medium" | "high" | "extreme"
    funding_rate: float = 0.0
    grid_efficiency: float = 0.0  # fills_per_hour


class VolatilityRegime(Enum):
    LOW = "low"           # < 5% 24h vol
    MEDIUM = "medium"     # 5-15%
    HIGH = "high"         # 15-30%
    EXTREME = "extreme"   # > 30%

    @classmethod
    def from_volatility(cls, vol_24h_pct: float) -> 'VolatilityRegime':
        if vol_24h_pct >= 30:
            return cls.EXTREME
        elif vol_24h_pct >= 15:
            return cls.HIGH
        elif vol_24h_pct >= 5:
            return cls.MEDIUM
        return cls.LOW


class RealTimeMonitor:
    """
    v5.3 Enhanced Real-Time Monitor with:
    - Performance history tracking (time-series snapshots)
    - Volatility regime detection & transition alerts
    - Auto grid adjustment suggestions
    - Webhook notification support
    - Aggregated performance statistics
    """

    def __init__(self, base_monitor: GridPerformanceMonitor,
                 snapshot_interval_sec: int = 300,
                 max_history: int = 288):
        self.base = base_monitor
        self.snapshot_interval = snapshot_interval_sec
        self.max_history = max_history  # 288 × 5min = 24h default
        self._history: Dict[str, deque] = {}  # symbol → deque[PerformanceSnapshot]
        self._vol_regimes: Dict[str, VolatilityRegime] = {}
        self._last_snapshot_time: Dict[str, float] = {}
        self._webhook_url: Optional[str] = None
        self._webhook_headers: Dict[str, str] = {"Content-Type": "application/json"}
        self._notification_callbacks: List[Callable] = []

    def set_webhook(self, url: str, headers: Optional[Dict[str, str]] = None):
        """Configure webhook URL for external alert notifications."""
        self._webhook_url = url
        if headers:
            self._webhook_headers.update(headers)

    def add_notification_callback(self, callback: Callable):
        """Register a callback function for alert notifications."""
        self._notification_callbacks.append(callback)

    def record_snapshot(self, symbol: str, price: float, pnl_pct: float,
                        fill_rate: float, vol_24h_pct: float,
                        funding_rate: float = 0.0,
                        total_fills: int = 0, runtime_hours: float = 0.0):
        """Record a performance snapshot for time-series tracking."""
        now = time.time()
        last = self._last_snapshot_time.get(symbol, 0)
        if now - last < self.snapshot_interval:
            return  # Too soon, skip

        regime = VolatilityRegime.from_volatility(vol_24h_pct)
        efficiency = total_fills / max(runtime_hours, 0.01)

        snap = PerformanceSnapshot(
            timestamp=datetime.now(),
            symbol=symbol,
            price=price,
            pnl_pct=pnl_pct,
            fill_rate=fill_rate,
            volatility_regime=regime.value,
            funding_rate=funding_rate,
            grid_efficiency=efficiency,
        )

        if symbol not in self._history:
            self._history[symbol] = deque(maxlen=self.max_history)
        self._history[symbol].append(snap)
        self._last_snapshot_time[symbol] = now

        # Detect volatility regime transition
        prev_regime = self._vol_regimes.get(symbol)
        if prev_regime and prev_regime != regime:
            self._on_regime_change(symbol, prev_regime, regime, vol_24h_pct)
        self._vol_regimes[symbol] = regime

    def _on_regime_change(self, symbol: str, old: VolatilityRegime,
                          new: VolatilityRegime, vol_pct: float):
        """Handle volatility regime transition — generate alert and suggestion."""
        direction = "升高" if new.value > old.value else "降低"
        level = AlertLevel.HIGH if new in (VolatilityRegime.EXTREME, VolatilityRegime.LOW) else AlertLevel.MEDIUM

        alert = Alert(
            id=str(uuid.uuid4())[:8],
            level=level,
            category="volatility_regime",
            symbol=symbol,
            message=(
                f"波动率regime变化: {old.value} → {new.value} "
                f"(24h vol={vol_pct:.1f}%) — 建议{self._get_regime_suggestion(new)}"
            ),
            value=vol_pct,
            threshold=0.0,
        )
        self.base.alert_history.append(alert)
        self._dispatch_notification(alert)

    def _get_regime_suggestion(self, regime: VolatilityRegime) -> str:
        """Get grid adjustment suggestion based on volatility regime."""
        suggestions = {
            VolatilityRegime.LOW: "缩小网格区间并减少网格数量至15-20，或暂停网格等待波动率回升",
            VolatilityRegime.MEDIUM: "维持当前网格参数，网格数量20-30为宜",
            VolatilityRegime.HIGH: "适当扩大网格区间，网格数量增至40，确保单格利润≥0.8%",
            VolatilityRegime.EXTREME: "立即扩大网格区间至±15%，降低杠杆至3×，考虑减仓",
        }
        return suggestions.get(regime, "")

    def suggest_grid_adjustment(self, symbol: str) -> Optional[Dict]:
        """Analyze recent performance and suggest grid parameter adjustments."""
        history = self._history.get(symbol)
        if not history or len(history) < 6:  # Need at least 30 min of data
            return None

        recent = list(history)[-12:]  # Last hour
        avg_pnl = sum(s.pnl_pct for s in recent) / len(recent)
        avg_fill = sum(s.fill_rate for s in recent) / len(recent)
        avg_efficiency = sum(s.grid_efficiency for s in recent) / len(recent)
        pnl_trend = recent[-1].pnl_pct - recent[0].pnl_pct
        current_regime = self._vol_regimes.get(symbol, VolatilityRegime.MEDIUM)

        suggestion = {
            "symbol": symbol,
            "current_regime": current_regime.value,
            "avg_pnl_1h": round(avg_pnl, 4),
            "avg_fill_rate_1h": round(avg_fill, 2),
            "avg_efficiency_fills_per_hour": round(avg_efficiency, 2),
            "pnl_trend_1h": round(pnl_trend, 4),
            "actions": [],
        }

        # Low fill rate → grid too wide
        if avg_fill < 10:
            suggestion["actions"].append({
                "type": "tighten_range",
                "reason": f"成交率仅{avg_fill:.1f}%，网格区间可能过宽",
                "recommendation": "缩小网格区间20-30%，或增加网格密度",
            })

        # Declining PnL → market trending against grid
        if pnl_trend < -1.0:
            suggestion["actions"].append({
                "type": "shift_range",
                "reason": f"PnL 1小时内下降{abs(pnl_trend):.2f}%，市场可能正在趋势化",
                "recommendation": "考虑移动网格中心价格至当前价，或暂停网格",
            })

        # High efficiency + positive PnL → grid is working well
        if avg_efficiency > 5 and avg_pnl > 0:
            suggestion["actions"].append({
                "type": "maintain",
                "reason": f"网格运行良好：每小时{avg_efficiency:.1f}次成交，PnL +{avg_pnl:.2f}%",
                "recommendation": "维持当前参数，继续监控",
            })

        # Extreme volatility → reduce risk
        if current_regime == VolatilityRegime.EXTREME:
            suggestion["actions"].append({
                "type": "reduce_risk",
                "reason": "当前处于极端波动率regime",
                "recommendation": "降低杠杆至3×，扩大止损距离至8%，减少仓位至5%",
            })

        return suggestion

    def get_performance_stats(self, symbol: str) -> Optional[Dict]:
        """Calculate aggregated performance statistics from snapshot history."""
        history = self._history.get(symbol)
        if not history or len(history) < 2:
            return None

        snaps = list(history)
        pnls = [s.pnl_pct for s in snaps]
        prices = [s.price for s in snaps]
        efficiencies = [s.grid_efficiency for s in snaps]

        # Time range
        start_time = snaps[0].timestamp
        end_time = snaps[-1].timestamp
        duration_hours = (end_time - start_time).total_seconds() / 3600

        # PnL stats
        max_pnl = max(pnls)
        min_pnl = min(pnls)
        current_pnl = pnls[-1]

        # Max drawdown from peak
        peak = pnls[0]
        max_drawdown = 0.0
        for p in pnls:
            if p > peak:
                peak = p
            dd = peak - p
            if dd > max_drawdown:
                max_drawdown = dd

        # Price range
        price_high = max(prices)
        price_low = min(prices)

        # Regime distribution
        regime_counts: Dict[str, int] = {}
        for s in snaps:
            regime_counts[s.volatility_regime] = regime_counts.get(s.volatility_regime, 0) + 1
        total = len(snaps)
        regime_pcts = {k: round(v / total * 100, 1) for k, v in regime_counts.items()}

        return {
            "symbol": symbol,
            "tracking_duration_hours": round(duration_hours, 2),
            "total_snapshots": len(snaps),
            "pnl": {
                "current": round(current_pnl, 4),
                "max": round(max_pnl, 4),
                "min": round(min_pnl, 4),
                "max_drawdown": round(max_drawdown, 4),
            },
            "price": {
                "current": round(prices[-1], 6),
                "high": round(price_high, 6),
                "low": round(price_low, 6),
                "range_pct": round((price_high - price_low) / price_low * 100, 2) if price_low > 0 else 0,
            },
            "efficiency": {
                "avg_fills_per_hour": round(sum(efficiencies) / len(efficiencies), 2),
                "max_fills_per_hour": round(max(efficiencies), 2),
            },
            "volatility_regime_distribution": regime_pcts,
        }

    def _dispatch_notification(self, alert: Alert):
        """Send alert via webhook and registered callbacks."""
        # Webhook
        if self._webhook_url and alert.level in (AlertLevel.CRITICAL, AlertLevel.HIGH):
            try:
                import requests as req
                payload = {
                    "source": "crayfish-grid-hunter",
                    "level": alert.level.value,
                    "symbol": alert.symbol,
                    "message": alert.message,
                    "timestamp": alert.timestamp.isoformat(),
                }
                req.post(self._webhook_url, json=payload,
                         headers=self._webhook_headers, timeout=5)
            except Exception:
                pass  # Non-blocking — don't let notification failure affect monitoring

        # Callbacks
        for cb in self._notification_callbacks:
            try:
                cb(alert)
            except Exception:
                pass

    def run_enhanced_checks(self) -> List[Alert]:
        """Run base checks + enhanced regime/adjustment checks."""
        alerts = self.base.run_checks()
        # Dispatch CRITICAL/HIGH alerts via webhook
        for a in alerts:
            if a.level in (AlertLevel.CRITICAL, AlertLevel.HIGH):
                self._dispatch_notification(a)
        return alerts

    def format_dashboard(self) -> str:
        """Generate a real-time dashboard view with performance stats."""
        lines = [
            "=" * 65,
            f"  CRAYFISH GRID HUNTER v5.3 — REAL-TIME DASHBOARD",
            f"  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "=" * 65,
        ]

        for symbol in self.base.positions:
            pos = self.base.positions[symbol]
            regime = self._vol_regimes.get(symbol, VolatilityRegime.MEDIUM)
            stats = self.get_performance_stats(symbol)

            status = "IN RANGE" if pos.price_in_range else "OUT OF RANGE"
            pnl_sign = "+" if pos.pnl_pct >= 0 else ""

            lines.append(f"\n  [{symbol}] {status} | Regime: {regime.value.upper()}")
            lines.append(f"    Price: {pos.current_price:.4f}  "
                         f"Range: [{pos.grid_lower:.4f}, {pos.grid_upper:.4f}]")
            lines.append(f"    PnL: {pnl_sign}{pos.pnl_pct:.2f}%  "
                         f"Fill Rate: {pos.fill_rate:.1f}%  "
                         f"Runtime: {pos.runtime_hours:.1f}h")

            if stats:
                lines.append(f"    Stats: Max PnL={stats['pnl']['max']:.2f}%  "
                             f"Max DD={stats['pnl']['max_drawdown']:.2f}%  "
                             f"Avg Fills/h={stats['efficiency']['avg_fills_per_hour']:.1f}")

            # Grid adjustment suggestion
            suggestion = self.suggest_grid_adjustment(symbol)
            if suggestion and suggestion["actions"]:
                for action in suggestion["actions"][:2]:  # Show top 2
                    lines.append(f"    Suggest: [{action['type']}] {action['recommendation']}")

        # Alert summary
        recent = self.base.alert_history[-5:]
        if recent:
            lines.append(f"\n  RECENT ALERTS")
            for a in recent:
                ts = a.timestamp.strftime("%H:%M:%S")
                lines.append(f"    [{ts}] [{a.level.value:<8}] {a.symbol}: {a.message[:60]}")

        lines.append("\n" + "=" * 65)
        return "\n".join(lines)


def create_realtime_monitor(
    webhook_url: Optional[str] = None,
    snapshot_interval_sec: int = 300,
    **kwargs,
) -> RealTimeMonitor:
    """Factory for creating a v5.3 enhanced real-time monitor."""
    base = create_monitor(**{k: v for k, v in kwargs.items()
                            if k in ('pnl_loss_critical_pct', 'pnl_loss_high_pct',
                                     'boundary_proximity_critical_pct',
                                     'stop_loss_proximity_critical_pct',
                                     'volume_spike_multiplier', 'api_latency_high_ms')})
    rt = RealTimeMonitor(base, snapshot_interval_sec=snapshot_interval_sec)
    if webhook_url:
        rt.set_webhook(webhook_url)
    return rt
